package com.handbrakers.entity;

// Generated 9 Sep, 2016 2:56:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DriverIdentityProfile generated by hbm2java
 */
@Entity
@Table(name = "driver_identity_profile")
public class DriverIdentityProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6362615292404754395L;
	private Long driverIdentityProfileId;
	private Users users;
	private String panCardNumber;
	private String drivingLicenceNumber;
	private String adhaarCardNumber;
	private boolean driverHavingVehicle;
	private String vehicleDetails;
	private boolean isPanVerified;
	private Date panVerifiedTs;
	private String panVerifiedBy;
	private boolean isDrivingLicenceVerified;
	private Date drivingLicenceVerifiedTs;
	private String drivingLicenceVerifiedBy;
	private boolean isAdhaarVerified;
	private Date adhaarVerifiedTs;
	private String adhaarVerifiedBy;

	public DriverIdentityProfile() {
	}

	public DriverIdentityProfile(Users users, String panCardNumber,
			String drivingLicenceNumber, String adhaarCardNumber,
			boolean driverHavingVehicle, boolean isPanVerified,
			Date panVerifiedTs, boolean isDrivingLicenceVerified,
			Date drivingLicenceVerifiedTs, boolean isAdhaarVerified,
			Date adhaarVerifiedTs) {
		this.users = users;
		this.panCardNumber = panCardNumber;
		this.drivingLicenceNumber = drivingLicenceNumber;
		this.adhaarCardNumber = adhaarCardNumber;
		this.driverHavingVehicle = driverHavingVehicle;
		this.isPanVerified = isPanVerified;
		this.panVerifiedTs = panVerifiedTs;
		this.isDrivingLicenceVerified = isDrivingLicenceVerified;
		this.drivingLicenceVerifiedTs = drivingLicenceVerifiedTs;
		this.isAdhaarVerified = isAdhaarVerified;
		this.adhaarVerifiedTs = adhaarVerifiedTs;
	}

	public DriverIdentityProfile(Users users, String panCardNumber,
			String drivingLicenceNumber, String adhaarCardNumber,
			boolean driverHavingVehicle, String vehicleDetails,
			boolean isPanVerified, Date panVerifiedTs, String panVerifiedBy,
			boolean isDrivingLicenceVerified, Date drivingLicenceVerifiedTs,
			String drivingLicenceVerifiedBy, boolean isAdhaarVerified,
			Date adhaarVerifiedTs, String adhaarVerifiedBy) {
		this.users = users;
		this.panCardNumber = panCardNumber;
		this.drivingLicenceNumber = drivingLicenceNumber;
		this.adhaarCardNumber = adhaarCardNumber;
		this.driverHavingVehicle = driverHavingVehicle;
		this.vehicleDetails = vehicleDetails;
		this.isPanVerified = isPanVerified;
		this.panVerifiedTs = panVerifiedTs;
		this.panVerifiedBy = panVerifiedBy;
		this.isDrivingLicenceVerified = isDrivingLicenceVerified;
		this.drivingLicenceVerifiedTs = drivingLicenceVerifiedTs;
		this.drivingLicenceVerifiedBy = drivingLicenceVerifiedBy;
		this.isAdhaarVerified = isAdhaarVerified;
		this.adhaarVerifiedTs = adhaarVerifiedTs;
		this.adhaarVerifiedBy = adhaarVerifiedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "driver_identity_profile_id", unique = true, nullable = false)
	public Long getDriverIdentityProfileId() {
		return this.driverIdentityProfileId;
	}

	public void setDriverIdentityProfileId(Long driverIdentityProfileId) {
		this.driverIdentityProfileId = driverIdentityProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "pan_card_number", nullable = false, length = 20)
	public String getPanCardNumber() {
		return this.panCardNumber;
	}

	public void setPanCardNumber(String panCardNumber) {
		this.panCardNumber = panCardNumber;
	}

	@Column(name = "driving_licence_number", nullable = false, length = 50)
	public String getDrivingLicenceNumber() {
		return this.drivingLicenceNumber;
	}

	public void setDrivingLicenceNumber(String drivingLicenceNumber) {
		this.drivingLicenceNumber = drivingLicenceNumber;
	}

	@Column(name = "adhaar_card_number", nullable = false, length = 50)
	public String getAdhaarCardNumber() {
		return this.adhaarCardNumber;
	}

	public void setAdhaarCardNumber(String adhaarCardNumber) {
		this.adhaarCardNumber = adhaarCardNumber;
	}

	@Column(name = "driver_having_vehicle", nullable = false)
	public boolean isDriverHavingVehicle() {
		return this.driverHavingVehicle;
	}

	public void setDriverHavingVehicle(boolean driverHavingVehicle) {
		this.driverHavingVehicle = driverHavingVehicle;
	}

	@Column(name = "vehicle_details", length = 500)
	public String getVehicleDetails() {
		return this.vehicleDetails;
	}

	public void setVehicleDetails(String vehicleDetails) {
		this.vehicleDetails = vehicleDetails;
	}

	@Column(name = "is_pan_verified", nullable = false)
	public boolean isIsPanVerified() {
		return this.isPanVerified;
	}

	public void setIsPanVerified(boolean isPanVerified) {
		this.isPanVerified = isPanVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pan_verified_ts", nullable = false, length = 19)
	public Date getPanVerifiedTs() {
		return this.panVerifiedTs;
	}

	public void setPanVerifiedTs(Date panVerifiedTs) {
		this.panVerifiedTs = panVerifiedTs;
	}

	@Column(name = "pan_verified_by")
	public String getPanVerifiedBy() {
		return this.panVerifiedBy;
	}

	public void setPanVerifiedBy(String panVerifiedBy) {
		this.panVerifiedBy = panVerifiedBy;
	}

	@Column(name = "is_driving_licence_verified", nullable = false)
	public boolean isIsDrivingLicenceVerified() {
		return this.isDrivingLicenceVerified;
	}

	public void setIsDrivingLicenceVerified(boolean isDrivingLicenceVerified) {
		this.isDrivingLicenceVerified = isDrivingLicenceVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "driving_licence_verified_ts", nullable = false, length = 19)
	public Date getDrivingLicenceVerifiedTs() {
		return this.drivingLicenceVerifiedTs;
	}

	public void setDrivingLicenceVerifiedTs(Date drivingLicenceVerifiedTs) {
		this.drivingLicenceVerifiedTs = drivingLicenceVerifiedTs;
	}

	@Column(name = "driving_licence_verified_by")
	public String getDrivingLicenceVerifiedBy() {
		return this.drivingLicenceVerifiedBy;
	}

	public void setDrivingLicenceVerifiedBy(String drivingLicenceVerifiedBy) {
		this.drivingLicenceVerifiedBy = drivingLicenceVerifiedBy;
	}

	@Column(name = "is_adhaar_verified", nullable = false)
	public boolean isIsAdhaarVerified() {
		return this.isAdhaarVerified;
	}

	public void setIsAdhaarVerified(boolean isAdhaarVerified) {
		this.isAdhaarVerified = isAdhaarVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "adhaar_verified_ts", nullable = false, length = 19)
	public Date getAdhaarVerifiedTs() {
		return this.adhaarVerifiedTs;
	}

	public void setAdhaarVerifiedTs(Date adhaarVerifiedTs) {
		this.adhaarVerifiedTs = adhaarVerifiedTs;
	}

	@Column(name = "adhaar_verified_by")
	public String getAdhaarVerifiedBy() {
		return this.adhaarVerifiedBy;
	}

	public void setAdhaarVerifiedBy(String adhaarVerifiedBy) {
		this.adhaarVerifiedBy = adhaarVerifiedBy;
	}

}
