package com.handbrakers.entity;

// Generated 9 Sep, 2016 2:56:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DriverAgencyIdentityProfile generated by hbm2java
 */
@Entity
@Table(name = "driver_agency_identity_profile")
public class DriverAgencyIdentityProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5682315697585500323L;
	private Long driverAgencyIdentityProfileId;
	private Users users;
	private String agencyName;
	private String agencyAddress;
	private String agencyRegistartionNumber;
	private String agencyContactNumber;
	private boolean isAgencyVerified;
	private Date agencyVerifiedTs;
	private String agencyVerifiedBy;
	private Set<DriverToDriverAgency> driverToDriverAgencies = new HashSet<DriverToDriverAgency>(
			0);

	public DriverAgencyIdentityProfile() {
	}

	public DriverAgencyIdentityProfile(Users users, String agencyName,
			String agencyAddress, String agencyRegistartionNumber,
			String agencyContactNumber, boolean isAgencyVerified,
			Date agencyVerifiedTs) {
		this.users = users;
		this.agencyName = agencyName;
		this.agencyAddress = agencyAddress;
		this.agencyRegistartionNumber = agencyRegistartionNumber;
		this.agencyContactNumber = agencyContactNumber;
		this.isAgencyVerified = isAgencyVerified;
		this.agencyVerifiedTs = agencyVerifiedTs;
	}

	public DriverAgencyIdentityProfile(Users users, String agencyName,
			String agencyAddress, String agencyRegistartionNumber,
			String agencyContactNumber, boolean isAgencyVerified,
			Date agencyVerifiedTs, String agencyVerifiedBy,
			Set<DriverToDriverAgency> driverToDriverAgencies) {
		this.users = users;
		this.agencyName = agencyName;
		this.agencyAddress = agencyAddress;
		this.agencyRegistartionNumber = agencyRegistartionNumber;
		this.agencyContactNumber = agencyContactNumber;
		this.isAgencyVerified = isAgencyVerified;
		this.agencyVerifiedTs = agencyVerifiedTs;
		this.agencyVerifiedBy = agencyVerifiedBy;
		this.driverToDriverAgencies = driverToDriverAgencies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "driver_agency_identity_profile_id", unique = true, nullable = false)
	public Long getDriverAgencyIdentityProfileId() {
		return this.driverAgencyIdentityProfileId;
	}

	public void setDriverAgencyIdentityProfileId(
			Long driverAgencyIdentityProfileId) {
		this.driverAgencyIdentityProfileId = driverAgencyIdentityProfileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "agency_name", nullable = false, length = 500)
	public String getAgencyName() {
		return this.agencyName;
	}

	public void setAgencyName(String agencyName) {
		this.agencyName = agencyName;
	}

	@Column(name = "agency_address", nullable = false, length = 500)
	public String getAgencyAddress() {
		return this.agencyAddress;
	}

	public void setAgencyAddress(String agencyAddress) {
		this.agencyAddress = agencyAddress;
	}

	@Column(name = "agency_registartion_number", nullable = false, length = 100)
	public String getAgencyRegistartionNumber() {
		return this.agencyRegistartionNumber;
	}

	public void setAgencyRegistartionNumber(String agencyRegistartionNumber) {
		this.agencyRegistartionNumber = agencyRegistartionNumber;
	}

	@Column(name = "agency_contact_number", nullable = false, length = 20)
	public String getAgencyContactNumber() {
		return this.agencyContactNumber;
	}

	public void setAgencyContactNumber(String agencyContactNumber) {
		this.agencyContactNumber = agencyContactNumber;
	}

	@Column(name = "is_agency_verified", nullable = false)
	public boolean isIsAgencyVerified() {
		return this.isAgencyVerified;
	}

	public void setIsAgencyVerified(boolean isAgencyVerified) {
		this.isAgencyVerified = isAgencyVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "agency_verified_ts", nullable = false, length = 19)
	public Date getAgencyVerifiedTs() {
		return this.agencyVerifiedTs;
	}

	public void setAgencyVerifiedTs(Date agencyVerifiedTs) {
		this.agencyVerifiedTs = agencyVerifiedTs;
	}

	@Column(name = "agency_verified_by")
	public String getAgencyVerifiedBy() {
		return this.agencyVerifiedBy;
	}

	public void setAgencyVerifiedBy(String agencyVerifiedBy) {
		this.agencyVerifiedBy = agencyVerifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driverAgencyIdentityProfile")
	public Set<DriverToDriverAgency> getDriverToDriverAgencies() {
		return this.driverToDriverAgencies;
	}

	public void setDriverToDriverAgencies(
			Set<DriverToDriverAgency> driverToDriverAgencies) {
		this.driverToDriverAgencies = driverToDriverAgencies;
	}

}
