package com.handbrakers.entity;

// Generated 9 Sep, 2016 2:56:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLoginFeed generated by hbm2java
 */
@Entity
@Table(name = "user_login_feed")
public class UserLoginFeed implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6079446292096510284L;
	private Long userLoginFeedId;
	private transient Users users;
	private String ipAddress;
	private Date loggedinTs;
	private Date loggedoutTs;

	public UserLoginFeed() {
	}

	public UserLoginFeed(Users users, String ipAddress, Date loggedinTs,
			Date loggedoutTs) {
		this.users = users;
		this.ipAddress = ipAddress;
		this.loggedinTs = loggedinTs;
		this.loggedoutTs = loggedoutTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_login_feed_id", unique = true, nullable = false)
	public Long getUserLoginFeedId() {
		return this.userLoginFeedId;
	}

	public void setUserLoginFeedId(Long userLoginFeedId) {
		this.userLoginFeedId = userLoginFeedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "ip_address", nullable = false, length = 50)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loggedin_ts", nullable = false, length = 19)
	public Date getLoggedinTs() {
		return this.loggedinTs;
	}

	public void setLoggedinTs(Date loggedinTs) {
		this.loggedinTs = loggedinTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loggedout_ts", nullable = false, length = 19)
	public Date getLoggedoutTs() {
		return this.loggedoutTs;
	}

	public void setLoggedoutTs(Date loggedoutTs) {
		this.loggedoutTs = loggedoutTs;
	}

}
