package com.handbrakers.entity;

// Generated 9 Sep, 2016 2:56:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLoginAttemptCount generated by hbm2java
 */
@Entity
@Table(name = "user_login_attempt_count")
public class UserLoginAttemptCount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2967053915157678159L;
	private Long userLoginAttemptCountId;
	private transient Users users;
	private int attemptCount;
	private Date lastAttemptTs;

	public UserLoginAttemptCount() {
	}

	public UserLoginAttemptCount(Users users, int attemptCount,
			Date lastAttemptTs) {
		this.users = users;
		this.attemptCount = attemptCount;
		this.lastAttemptTs = lastAttemptTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_login_attempt_count_id", unique = true, nullable = false)
	public Long getUserLoginAttemptCountId() {
		return this.userLoginAttemptCountId;
	}

	public void setUserLoginAttemptCountId(Long userLoginAttemptCountId) {
		this.userLoginAttemptCountId = userLoginAttemptCountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "attempt_count", nullable = false)
	public int getAttemptCount() {
		return this.attemptCount;
	}

	public void setAttemptCount(int attemptCount) {
		this.attemptCount = attemptCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_attempt_ts", nullable = false, length = 19)
	public Date getLastAttemptTs() {
		return this.lastAttemptTs;
	}

	public void setLastAttemptTs(Date lastAttemptTs) {
		this.lastAttemptTs = lastAttemptTs;
	}

}
