package com.handbrakers.entity;

// Generated 9 Sep, 2016 2:56:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserToRole generated by hbm2java
 */
@Entity
@Table(name = "user_to_role")
public class UserToRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 939977963389051978L;
	private Long userToRoleId;
	private Users users;
	private Roles roles;

	public UserToRole() {
	}

	public UserToRole(Users users, Roles roles) {
		this.users = users;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_to_role_id", unique = true, nullable = false)
	public Long getUserToRoleId() {
		return this.userToRoleId;
	}

	public void setUserToRoleId(Long userToRoleId) {
		this.userToRoleId = userToRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
